# Generated by Django 4.1 on 2022-10-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='pruebareal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='calificacionprueba',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
