# Generated by Django 4.1 on 2022-10-04 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_estudiantepruebas_nombre_completo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiantepruebas',
            old_name='nombre_completo',
            new_name='nombre_completoo',
        ),
    ]
